version: "3.9"
services:
  backend:
    build: ./backend
    container_name: rag-backend
    env_file: .env
    volumes:
      - ./vectorstore/faiss_index:/data/index
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: rag-frontend
    env_file: .env
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    ports:
      - "8501:8501"
networks:
  default:
    name: rag-net
